feat: MOZO-150 show all class users & customize results depending on communication rules
edificeio/entcore pull request #450
Opened 2024-03-08 14:05 UTC by zban-ode

# Description

A user must be able to see all students/tachers in the 'My Class' view regardless of communication rights, but he cannot communicate with them.

## Fixes

https://edifice-community.atlassian.net/browse/MOZO-150

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [x] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

1. Describe here the tests you performed
2. Step by step
3. With expected results

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [ ] All done ! :smiley:

2024-03-11 14:22 UTC, juniorode requested changes

2024-03-11 14:22 UTC, juniorode commented on directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
> +					String query_class_users = "MATCH " + matchClass +
Il faut nommer les variables en _camelCase_

2024-03-11 15:22 UTC, zban-ode commented on directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
> +		UserUtils.getUserInfos(eb, request, userInfo -> {
Done !

2024-03-21 08:56 UTC, dboissin commented
Je ne pige pas. Pouquoi tu veux merge dans develop-b2school ? Il te faudrait un develop-mozo.

2024-03-21 09:00 UTC, zban-ode commented
C'est pour déployer sur recette-ode1 en attendant que la recette-ode3 dédiée à MOZO soit libérée (actuellement utilisée par l'upgrade vertx).

2024-03-21 09:14 UTC, zban-ode commented
> Je ne pige pas. Pouquoi tu veux merge dans develop-b2school ? Il te faudrait un develop-mozo.

C'est pour déployer sur recette-ode1 en attendant que la recette-ode3 dédiée à MOZO soit libérée (actuellement utilisée par l'upgrade vertx).

2024-03-22 13:29 UTC, merged