feat(workspace): #WB-2679, direct transfer of documents to protected or public space
edificeio/entcore pull request #468
Opened 2024-04-03 12:33 UTC by jcbe-ode

# Description

Ce endpoint permet de transférer, en un seul appel, plusieurs documents de l'utilisateur 
* depuis le dossier "Mes documents" ou "Partagés avec moi" 
* vers le pseudo-dossier "Partagé dans mes applis" (visibility=protected) ou "Publics" (visibility=public)

Un tableau de documents est retourné, dans le même ordre que les ids spécifiés dans le corps de la requête. 
Tout document retourné à `null` signifie que son transfert a échoué, ou que le document demandé n'existaient pas.

En interne, si un document est transféré vers l'espace `protected` ou `public`, alors une copie des fichiers est effectuée, et l'original est conservé intact.
S'il passe de `protected` à `public` ou inversement, seule l'indexation en DB change. Les fichiers sont conservés.

Ce comportement imite le fonctionnement historique de la MediaLibrary, où tout document mis `protected` ou `public` était téléchargé par le client web, avant d'être ré-uploadé au bon endroit. On économise ainsi de la bande passante.

## Fixes

[WB-2679](https://edifice-community.atlassian.net/browse/WB-2679)

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [X] common
- [ ] communication
- [ ] conversation
- [ ] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [X] workspace

## Tests

Tests manuels seulement.
J'ai testé les différentes combinaisons, avec point d'arrêt dans le débogueur puis déroulé pas à pas, afin de vérifier la justesse de l'algorithme implémenté.

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [X] All done ! :smiley:

2024-04-03 13:41 UTC, juniorode commented on common/src/main/java/org/entcore/common/folders/FolderManager.java
> +	void copyAllNoFail(Optional<UserInfos> userOpt, List<JsonObject> originals,
Il faudrait renvoyer un `Future` plutôt que prendre un Handler en paramètre pour :
1. la composabilité
2. une meilleure possibilité de traiter les erreurs
3. la classe `Handler` est dépréciée dans Vertx4 et sera bientôt retirée

2024-04-03 14:21 UTC, juniorode requested changes

2024-04-03 14:21 UTC, juniorode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +			return CompositeFuture.join(futures)
si tu t'arrêtes à ce `return` tu peux ensuite mettre le `compose` et le `recover` qui suivent en dehors de ce `compose` (pour diminuer l'imbrication)

2024-04-03 14:46 UTC, mariusode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +			.recover( unused -> Future.succeededFuture(null) ) // never fails this copy
Je suis pas à l'aise avec l'idée de manipuler potentiellement des null. Peut-être les wrapper des des Optionals pour forcer la vérif ?

2024-04-03 14:46 UTC, mariusode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +					return (JsonObject) null;
Idem, je suis pas forcément à l'aise avec les `continue` et `return` dans des `if` sans `else`. Je trouve ça moins "exhaustif" à la lecture.

2024-04-03 14:46 UTC, mariusode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +				//InheritShareComputer.mergeShared(parent, copy, true);
Du coup le mergeShared n'est plus nécessaire ?

2024-04-03 14:46 UTC, mariusode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +		// Persist the copied documents in DB
Est-ce que cette implémentation avec recopies d'abord & persistence ensuite ne pourrait pas être scindée en deux méthodes privées avec une responsabilité chacune ?

2024-04-03 14:46 UTC, mariusode commented on common/src/main/java/org/entcore/common/folders/impl/StorageHelper.java
> +	/** Remove fileIds from the document, if they match the document's file or any thumbnail. */
Peut-être générer la javadoc avec les standards @param pour la description des arguments ?

2024-04-03 14:46 UTC, mariusode commented on common/src/main/java/org/entcore/common/folders/impl/StorageHelper.java
> +		final Set<Map.Entry<String,Object>> thumbnailEntries = thumbnails==null ? null : thumbnails.getMap().entrySet();
Plutôt que de manipuler un Set de Entries<>, pourquoi ne pas faire un .stream() directement sur la Map<> ?

2024-04-03 14:46 UTC, mariusode commented on common/src/main/java/org/entcore/common/folders/impl/StorageHelper.java
> +		final List<Future> copyFutures = new ArrayList<Future>();
Il me semble que `List<Future<?>>` suffit à éviter le warning, mais je sais pas si c'est une bonne pratique.

2024-04-03 14:46 UTC, mariusode commented on workspace/src/main/java/org/entcore/workspace/service/WorkspaceService.java
> +	public void transferAll(final List<String> sourceIds, Optional<String> application, Visibility visibility, UserInfos user,
Idem, `return Future<>` plutôt que `Handler<>` en param

2024-04-03 14:46 UTC, jcbe-ode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +		for( int i = 0; i<originals.size(); i++ ) {
Par contre, ça met en évidence un bug potentiel :D

2024-04-03 15:05 UTC, jcbe-ode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +			return CompositeFuture.join(futures)
Ce n'est pas possible, car c'est bien la liste `futures` qu'il me faut récupérer ensuite dans le `.map()` au-dessous.

En théorie, il aurait même fallu gérer un pseudo-rollback et supprimer les fichiers dupliqués auparavant), avant de mettre à jour la liste `futures` en conséquence. Mais ça, c'est dans un monde idéal.

2024-04-04 06:38 UTC, jcbe-ode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +			.recover( unused -> Future.succeededFuture(null) ) // never fails this copy
Je ne suis pas fan des Optional, qui alourdissent le code et le rendent plus dur à lire (à mon sens).
Pour autant, j'essaie aussi d'éviter les null en général, mais cette méthode doit précisément mettre des null dans la liste retournée, au lieu de JsonObject, lorsque la copie d'un document échoue.

2024-04-04 09:48 UTC, juniorode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +		for( int i = 0; i<originals.size(); i++ ) {
Si tu passes par un `stream` t'auras pas besoin de faire `set(i, XXX)`.

2024-04-04 09:55 UTC, juniorode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +			return CompositeFuture.join(futures)
Ok je vois :+1:

2024-04-04 09:57 UTC, juniorode requested changes

2024-04-04 09:57 UTC, juniorode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
>  				.compose(unused -> Future.succeededFuture(futures))
```suggestion
				.map(unused -> futures)
```

2024-04-04 11:12 UTC, jcbe-ode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +		// Persist the copied documents in DB
Si, j'avais hésité à refacto le code, mais tu as fini de me convaincre :-)

2024-04-04 11:26 UTC, jcbe-ode commented on common/src/main/java/org/entcore/common/folders/impl/StorageHelper.java
> +		final Set<Map.Entry<String,Object>> thumbnailEntries = thumbnails==null ? null : thumbnails.getMap().entrySet();
Cette partie utilise désormais des Pair plutôt que des Map.Entry

Mais pour répondre à ta question, le code proposé reproduisait l'esprit du code pré-existant déjà dans le même fichier.

J'essaie généralement de coder "au même niveau" que l'existant, de manière à ce que l'ensemble reste cohérent et qu'un relecteur n'ait pas à connaître X versions du langage ou d'un framework.
Cette pratique a l'inconvénient de créer de la dette technique dès l'écriture, mais a l'avantage de rester uniforme et à la portée du relecteur (s'il peut lire une partie du code, il peut lire tout le code) quitte à spécialiser la maintenance d'une partie de l'appli.
Le problème de la dette technique existe déjà, et ne sera pas complexifié si on rajoute 1 fonction de plus...
Alors qu'en mixant différents niveaux de code, ça pourrait compliquer ou limiter les solutions possibles.

2024-04-04 13:00 UTC, jcbe-ode commented on common/src/main/java/org/entcore/common/folders/impl/FolderManagerMongoImpl.java
> +			.recover( unused -> Future.succeededFuture(null) ) // never fails this copy
Je les ai mis après refacto du code en plusieurs fonctions distinctes, c'est plus clair.

2024-04-04 15:42 UTC, juniorode approved these changes

2024-04-05 06:09 UTC, merged