Feat wb 3184 user positions
edificeio/entcore pull request #503
Opened 2024-08-02 14:20 UTC by mariusode

# Description

Une première implémentation des aspects backends des UserPositions (chantier nouveau champ Fonctions) avec contrôle sur les droits d'admin.

## Fixes

Cette PR comporte les travaux d'implémentation de plusieurs tickets :
- modification du endpoint de création d'un utilisateur: https://edifice-community.atlassian.net/browse/WB-3188
- modification des fonctions d'un utilisateur: https://edifice-community.atlassian.net/browse/WB-3190
- récupération des informations d'un utilisateur: https://edifice-community.atlassian.net/browse/WB-3189
- implémentation des endpoints CRUD: https://edifice-community.atlassian.net/browse/WB-3184
- modélisation neo4j: https://edifice-community.atlassian.net/browse/WB-3185

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [x] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

Tests de dev manual sur les différents endpoints CRUD

Manquent des tests approfondis sur les aspects : 
- modification du endpoint de création d'un utilisateur
- modification des fonctions d'un utilisateur
- récupération des informations d'un utilisateur

➡️ à tester avec la connexion au back/front ?

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [ ] All done ! :smiley:

2024-08-06 09:33 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/controllers/UserController.java
> +						final Set<String> userPositionIds = new HashSet<>(RequestUtils.getParamAsSet("positionIds", request));
On passe les `positionIds` via query parameters ?
Le body de la query est un JSON contenant les données de l'utilisateur à modifier. Côté front, la génération de ce body est plutôt automatisée, il sera peut-être plus simple d'adapter le back...

PS : passer les `positionIds` via le body nécessiterait aussi de changer le jsonschema à respecter : https://github.com/edificeio/entcore/blob/92d029f053a9b8fb0e804f7014fef9a5ca9f6569/directory/src/main/resources/jsonschema/updateUser.json

2024-08-06 12:02 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserPositionService.java
> +		return promise.future();
```suggestion
                //TODO neo4jClient.execute(...
		return promise.future();
```

2024-08-06 12:19 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/controllers/UserController.java
> +											if (!userPositionIds.isEmpty()) {
```suggestion
											if (userPositionIds!=null) {
```
Attention à bien distinguer les 3 cas de figures : 
- aucun query param `positionIds` => le graphe ne doit pas être modifié, le User conserve ses liens existant avec tout noeud UserPosition.
- `positionIds` sans valeur => équivaut à un tableau vide, il faut supprimer tout lien existant entre le User et un noeud UserPosition.
- `positionIds` avec une ou plusieurs valeurs => ajouter les liens manquants, et supprimer ceux existant qui ne sont pas dans le tableau.

En pratique, les 2 derniers cas sont bien gérés par le code proposé. **Il manque à gérer le 1er cas.**

2024-08-08 13:00 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
> +				"OPTIONAL MATCH u-[h:HAS_POSITION]->(p:UserPosition) WITH COLLECT(distinct {id: p.id, name: p.name, source: p.source}) as userPositions, subjectCodes, admStruct, admGroups, parents, children, fun
Extraire aussi l'ID de la structure de rattachement de chaque UserPosition ?
Sans cette information, le frontend ne pourra pas filtrer les positions sur la/les structure(s) concernées, sauf à charger la liste de toutes les positions existant et à croiser les données.

2024-08-12 09:09 UTC, juniorode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserPositionService.java
> +		final String query = "" +
@juniorode à voir

2024-08-12 16:26 UTC, juniorode requested changes

2024-08-12 16:26 UTC, juniorode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserPositionService.java
> +						Set<UserPosition> userPositions = new TreeSet<>();
Pourquoi `TreeSet` plutôt que `HashSet` ?

2024-08-13 08:51 UTC, mariusode commented on directory/src/main/java/org/entcore/directory/controllers/UserController.java
> +						final Set<String> userPositionIds = new HashSet<>(RequestUtils.getParamAsSet("positionIds", request));
Done

2024-08-13 08:51 UTC, mariusode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserPositionService.java
> +		return promise.future();
Done

2024-08-13 08:51 UTC, mariusode commented on directory/src/main/java/org/entcore/directory/controllers/UserController.java
> +											if (!userPositionIds.isEmpty()) {
Done

2024-08-13 08:51 UTC, mariusode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
> +				"OPTIONAL MATCH u-[h:HAS_POSITION]->(p:UserPosition) WITH COLLECT(distinct {id: p.id, name: p.name, source: p.source}) as userPositions, subjectCodes, admStruct, admGroups, parents, children, fun
Done

2024-08-13 08:51 UTC, mariusode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserPositionService.java
> +		final String query = "" +
Done

2024-08-13 08:52 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/controllers/UserController.java
> +						final Set<String> userPositionIds = new HashSet<>(RequestUtils.getParamAsSet("positionIds", request));
Alors je vais adapter le front en concordance ;-)

2024-08-14 10:13 UTC, jcbe-ode reviewed
Je poste déjà ces commentaires, et continue la revue avec le nouveau commit en +

2024-08-14 10:13 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
> +	public void createInStructure(String structureId, List<String> userPositionIds, JsonObject user, Handler<Either<String, JsonObject>> result) {
Avant modification, la méthode s'appelait `createUserInStructure` et prenait en paramètre un user et une structure.

Maintenant, la méthode s'appelle pareil mais prend aussi un paramètre `List<String> userPositionIds` qui va avoir des impacts différents sur la BDD selon qu'il soit `null`, _empty_ ou valorisé.
Ca va causer des incompréhensions chez les devs ne connaissant pas la notion de UserPosition.

Pour un _create_ ça passe encore, mais pour un _update_, la différence est subtile et ne saute pas aux yeux.

2024-08-14 10:13 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/services/impl/DefaultUserService.java
> +	public void update(final String id, final JsonArray userPositionIds, final JsonObject user, final Handler<Either<String, JsonObject>> result) {
J'ai peur qu'à terme on appelle cette fonction avec un tableau vide en pensant bien faire. Sauf que ça va vider les liens HAS_POSITION existants.

=> Utiliser un `Optional` ?

2024-08-14 12:47 UTC, jcbe-ode commented
Revue terminée, pas d'autres commentaires pour ma part.
A voir si vous êtes raccords avec moi sur ces points, mais rien de bloquant dans tous les cas.
Bon boulot !

2024-09-12 11:35 UTC, closed without merging