feat(common, directory): WB-3252, add UserPosition support in directory search criteria (backend)
edificeio/entcore pull request #512
Opened 2024-08-26 15:09 UTC by jcbe-ode

# Description

Ajout de la liste de positions aux critères de recherche dans directory, qui sont gérés par le backend.

Le développement a consisté à interroger le UserPositionService pour un utilisateur lambda,
et a enrichir les critères de recherche renvoyés au frontend.

## Fixes

[WB-3252](https://edifice-community.atlassian.net/browse/WB-3252)

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [X] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [X] common
- [ ] communication
- [ ] conversation
- [X] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

1. Describe here the tests you performed
2. Step by step
3. With expected results

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [ ] All done ! :smiley:

2024-08-29 14:51 UTC, Romu-C approved these changes

2024-08-30 09:48 UTC, juniorode requested changes

2024-08-30 09:50 UTC, juniorode commented on directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
> +				Future<Set<UserPosition>> userPositions = (monoStructureOnly && mainStructureId!=null)
Pour lancer les tests en question il faut faire 
```shell
cd /opt/projects/entcore/tests/src/test/js/it/scenarios/position
./run.sh
```
Tu devrais avoir une sortie qui te dit qqchose comme :
```shell
       █ ADML with a structure with these positions

         ✗ should have the same number of positions as expected
          ↳  0% — ✓ 0 / ✗ 1
         ✗ should contain all expected positions
          ↳  0% — ✓ 0 / ✗ 1

       █ ADML of multiple structures

         ✗ should have the same number of positions as expected
          ↳  0% — ✓ 0 / ✗ 1
         ✗ should contain all expected positions
          ↳  0% — ✓ 0 / ✗ 1
```

2024-08-30 12:39 UTC, mariusode commented on common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
> +	private Future<Set<UserPosition>> getUserPositions(String positionId, String prefix, String structureId, UserInfos userInfos) {
Cette méthode contient beaucoup de code en commun avec getAdminUserPosition.
Est-ce que ça ne vaudrait pas le coup de mutualiser ?

2024-08-30 16:02 UTC, jcbe-ode commented on directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
> +				Future<Set<UserPosition>> userPositions = (monoStructureOnly && mainStructureId!=null)
Feedback pris en compte, mais pour l'instant je ne parviens pas à faire fonctionner les tests.

2024-09-02 07:03 UTC, juniorode commented on directory/src/main/java/org/entcore/directory/controllers/UserBookController.java
> +				Future<Set<UserPosition>> userPositions = (monoStructureOnly && mainStructureId!=null)
Je vais voir de mon côté.

2024-09-03 08:07 UTC, jcbe-ode commented
Merge de la branche pour déploiement et free-tests.
Les tests (TDD) seront déroulés via un autre ticket.

2024-09-03 08:08 UTC, merged