test: #WB-3339, tests for user positions during AAF imports
edificeio/entcore pull request #527
Opened 2024-09-19 13:44 UTC by juniorode

# Description

- Création des tests d'intégration et des jeux de données pour vérifier la gestion des fonctions venant d'un import AAF
- Mise à jour de la tâche itTests du build.sh pour permettre l'exécution de script sh durant la phase de TIs

## Fixes

WB-3339

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [x] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [ ] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [x] tests
- [ ] timeline
- [ ] workspace

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [x] All done ! :smiley:

2024-10-17 07:06 UTC, jcbe-ode commented on tests/src/test/js/it/scenarios/position/csv-import.js
> +        const structure = createStructure(schoolName, teacherDataBefore, session)
Après exécution des tests, cette structure ne sera plus jamais utilisée.
Possibilité de la supprimer après des tests concluants ? Ou sinon, de toujours réutiliser la même structure ?

2024-10-17 08:29 UTC, jcbe-ode commented on feeder/src/main/java/org/entcore/feeder/dictionary/users/PersEducNat.java
> +								"MATCH (p:UserPosition)-[:IN]->(s:Structure {externalId : {structureExternalId}}), (u:User {externalId : {userExternalId}}) " +
Il faudrait idéalement placer cette requête dans le UserPositionService, dans une méthode paramétrée avec 
le transactionHelper en entrée.

2024-10-17 08:43 UTC, jcbe-ode commented on feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java
> +				"MATCH (s:Structure {id : {id}})<-[:IN]-(p:UserPosition) " +
```suggestion
				"MATCH (s:Structure {id : {id}})<-[:IN]-(p:UserPosition {source:\"CSV\"}) " +
```
et supprimer le WHERE.

2024-10-17 08:47 UTC, jcbe-ode commented on feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java
> +				"MATCH (u:User)-[hasPosition:HAS_POSITION]->(:UserPosition)-[:IN]->(s:Structure) " +
```suggestion
				"MATCH (u:User {externalId: {userExternalId}})-[hasPosition:HAS_POSITION]->(:UserPosition)-[:IN]->(s:Structure {externalId: {structureExternalId}}) " +
```

2024-10-17 09:19 UTC, jcbe-ode reviewed
Quelques commentaires / questions, sinon OK pour moi.

2024-10-17 15:31 UTC, mariusode commented on tests/src/test/js/it/scenarios/position/csv-import.js
> +        const structure = createStructure(schoolName, teacherDataBefore, session)
Ouais on en avait discuté avec @juniorode, il me répondait qu'en réalité ces tests ont vocation à être joués avec des recette "fraichement" créées puis supprimées, donc a priori la base neo4j associée n'existe que le temps du temps.
Je peux quand même regarder pour rejouer sur la même structure si elle exsite. Mais du coup il faudra que je fasse un clean des positions dans un teardown à la fin du deuxième import, comme dans le cas des csv.

2024-10-18 14:46 UTC, mariusode commented on feeder/src/main/java/org/entcore/feeder/csv/CsvFeeder.java
> +				if (g.length != 2) {
Ça correspond à la section "Fonction au format simple" à cet [endroit de la spec](https://edifice-community.atlassian.net/wiki/spaces/ODE/pages/3742105606/Cadrage+fonctionnel+Am+lioration+du+champ+fonction#Modification-des-traitements-des-CSV-NEW)

2024-10-18 14:51 UTC, mariusode commented on feeder/src/main/java/org/entcore/feeder/dictionary/structures/Importer.java
> +	public void removeUnusedAAFPositions() {
Pour les CSV, on ne [supprime pas les fonctions au réimport de fichier](https://edifice-community.atlassian.net/wiki/spaces/ODE/pages/3742105606/Cadrage+fonctionnel+Am+lioration+du+champ+fonction#Suppression-d%E2%80%99une-fonction-cr%C3%A9%C3%A9e-depuis-un-CSV).

2024-10-18 14:52 UTC, mariusode commented on feeder/src/main/java/org/entcore/feeder/dictionary/structures/Importer.java
> +	public void removeUnusedAAFPositions() {
Bonne question pour le 1D, je regarde.

2024-10-18 15:13 UTC, mariusode commented on common/src/main/java/org/entcore/common/user/position/impl/DefaultUserPositionService.java
> +				"MERGE (s)<-[:IN]-(p:UserPosition {name : {positionName}}) " +
Je t'avoue qu'on ne s'est pas posé la question.
Quand je bossais avec un triplestore RDF, tant que les classes du sujet et de l'objet d'une relation pouvaient différer, on ne s'interdisait pas de réemployer la même classe pour le prédicat entre les deux.

2024-10-18 15:14 UTC, mariusode commented on feeder/src/main/java/org/entcore/feeder/dictionary/structures/Importer.java
> +	public void removeUnusedAAFPositions() {
J'ai rajouté pour le 1D, j'étais passé à côté je pense.

2024-10-21 09:24 UTC, jcbe-ode requested changes
* 2 requêtes à déplacer
* revoir les specs fonctionnelles concernant les imports/transitions

2024-10-21 09:24 UTC, jcbe-ode commented on feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java
> +				"MATCH (u:User {externalId: {userExternalId}})-[hasPosition:HAS_POSITION]->(:UserPosition)-[:IN]->(s:Structure {externalId: {structureExternalId}}) " +
Je décale cette requête dans le service dédié.

2024-10-21 09:24 UTC, jcbe-ode commented on feeder/src/main/java/org/entcore/feeder/dictionary/structures/Structure.java
> +				"DETACH DELETE p";
Je décale cette requête dans le service dédié.

2024-10-22 08:01 UTC, jcbe-ode commented
A la question "Pourquoi à la transition pour CSV et à tous les imports pour les AAF ?"
=> voir [specs ici.](https://edifice-community.atlassian.net/wiki/spaces/ODE/pages/3742105606/Cadrage+fonctionnel+Am+lioration+du+champ+fonction#Import-d%E2%80%99un-CSV-avec-l%E2%80%99option-transition-d%E2%80%99ann%C3%A9e)

2024-10-22 08:03 UTC, jcbe-ode approved these changes

2024-10-22 08:55 UTC, merged