feat(directory): WB-1699, restore custom sort on listIsolated method
edificeio/entcore pull request #532
Opened 2024-09-26 12:14 UTC by jcbe-ode

# Description

Réhabiliter le tri paramétrable sur la méthode DefaultUserService.listIsolated().
Ajouter des tests d'intégration.

## Fixes

[WB-1699](https://edifice-community.atlassian.net/browse/WB-1699)

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [X] Bug fix (PATCH)
- [ ] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [X] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

* Via Postman `/directory/list/isolated`
Le tri custom ne semble pas utilisé dans l'ENT.

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [X] All done ! :smiley:

2024-09-26 14:17 UTC, juniorode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +  let res = http.get(`${rootUrl}/directory/list/isolated?${params}`, undefined, {headers});
pourquoi `undefined` en 2ème paramètre ? Je pense que tu peux l'enlever.

2024-09-26 14:18 UTC, juniorode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +  if (res.status !== 200) {
```java
checkOk(res, `Impossible to list isolated users with query params ?${params}`)
```

2024-09-26 14:20 UTC, juniorode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +function getUserByName(structure, firstName, lastName, session) {
Plutôt
```javascript
const users = getUsersOfSchool(structure, session)
return users.filter(
    u => u.firstName === firstName && u.lastName === lastName
  )[0]
```

2024-09-26 14:28 UTC, juniorode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +export function createUser(structure, firstName, lastName, type, session) {
Cette fonction existe déjà https://github.com/edificeio/edifice-k6-commons/blob/develop/src/user.utils.ts#L192

2024-09-26 14:29 UTC, juniorode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +      undefined,
je pense qu'il n'y a pas besoin de ce paramètre `undefined`

2024-09-26 14:33 UTC, juniorode commented on tests/src/test/js/it/scenarios/isolated_users/list.js
> +  checks[`${requesterType} should be able to list 4 isolated users`] = () => {
Tu peux enlever le 4 du nom de la vérification parce qu'en soi la valeur ne porte pas de sens. `xxx should be able to list all isolated users` c'est plutôt pas mal

2024-09-26 14:35 UTC, juniorode commented on tests/src/test/js/it/scenarios/isolated_users/list.js
> +    let isDescendingOrder = isAnArray ? true : false;
Équivalent à 
```javascript
let isDescendingOrder = isAnArray;
```

2024-09-27 12:23 UTC, jcbe-ode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +  let res = http.get(`${rootUrl}/directory/list/isolated?${params}`, undefined, {headers});
L'analyseur syntaxique de mon IDE se fâche sans ça... Je vais mettre `null` à la place.

2024-09-27 12:34 UTC, jcbe-ode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +export function createUser(structure, firstName, lastName, type, session) {
Ok, renommé en `getOrCreateUser` et fait appel à la fonction `createUser` existante au lieu de réimplémenter.

2024-09-27 13:06 UTC, jcbe-ode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +      undefined,
Remplacé par null pour satisfaire mon IDE.

2024-09-27 13:11 UTC, jcbe-ode commented on tests/src/test/js/it/scenarios/isolated_users/list.js
> +    let isDescendingOrder = isAnArray ? true : false;
Algorithme simplifié en supprimant les variables superflues.

2024-09-27 13:37 UTC, juniorode commented on tests/src/test/js/it/scenarios/admin/utils.js
> +  let res = http.get(`${rootUrl}/directory/list/isolated?${params}`, undefined, {headers});
Tu peux l'enlever complètement, http.get ne prend que 2 paramètres
https://grafana.com/docs/k6/latest/javascript-api/k6-http/get/

2024-09-27 13:45 UTC, juniorode requested changes

2024-09-27 13:45 UTC, juniorode commented on tests/src/test/js/it/scenarios/isolated_users/list.js
> +      console.error('isDescendingOrder', isDescendingOrder);
`isDescendingOrder` n'existe pas (plus)

2024-09-30 08:53 UTC, jcbe-ode commented on tests/src/test/js/it/scenarios/isolated_users/list.js
> +      console.error('isDescendingOrder', isDescendingOrder);
Remplacé par un message d'erreur explicite

2024-10-01 12:23 UTC, merged