feat(conversation): WB-3630, added 3 new endpoints
edificeio/entcore pull request #559
Opened 2024-12-17 16:31 UTC by jcbe-ode

# Description

* Correction/modifiaction de scripts/conf maven + docker + jenkins (à discuter)
* Ajout de 3 nouveaux endpoints pour conversation (to be reviewed).

Cette PR contient la PR https://github.com/edificeio/entcore/pull/558 dont elle dépend, je la mettrai à jour une fois l'autre PR mergée.

## Fixes

[WB-3630](https://edifice-community.atlassian.net/browse/WB-3630)

## Type of change

Please check options that are relevant.

- [ ] Chore (PATCH)
- [ ] Doc (PATCH)
- [ ] Bug fix (PATCH)
- [ ] New feature (MINOR)

## Which packages changed?

Please check the name of the package you changed

- [ ] admin
- [ ] app-registry
- [ ] archive
- [ ] auth
- [ ] cas
- [ ] common
- [ ] communication
- [ ] conversation
- [ ] directory
- [ ] feeder
- [ ] infra
- [ ] portal
- [ ] session
- [ ] test
- [ ] tests
- [ ] timeline
- [ ] workspace

## Tests

1. Describe here the tests you performed
2. Step by step
3. With expected results

# Reminder

- Security flaws
- Performance impacts (think bulk !)
- Unit tests were replayed
- Unit tests were added and/or changed
- I have updated the reminder for the version including my modifications

- [ ] All done ! :smiley:

2024-12-18 09:04 UTC, juniorode requested changes
Il faudrai :
- laisser les fichiers gradle.properties supprimés
- modifier le gulpfile.js
- laisser l'appel à init

2024-12-19 13:16 UTC, mariusode commented on directory/src/main/java/org/entcore/directory/services/GroupService.java
> +	enum Field {
Je suis pas très familier du fonctionnement et de l'utilisation de ce genre d'enum avec des bitmask, je veux bien une explication à l'occasion :)

2024-12-19 16:33 UTC, jcbe-ode commented on conversation/backend/src/main/java/org/entcore/conversation/controllers/ApiController.java
> +			return;
Je comprends : j'utilise les `return` quasi-exclusivement lors des checks de variables en tout début de fonction, afin d'éviter un dérapage de l'indentation du code, mais évite sinon de les utiliser en règle générale.

2024-12-19 17:08 UTC, jcbe-ode commented on conversation/backend/src/main/java/org/entcore/conversation/util/FolderUtil.java
> +            while( compared < 0 && rootsIterator.hasNext() ) {
Le tableau `rootFolders` est triés par ID distincts croissant, et `subFolders` par parentId croissants.
On itère sur `subFolders` (donc par parentId strictement croissant) et en parallèle, on itère sur `rootFolders` (donc par ID strictement croissant).
=> Si l'ID courant est strictement inférieur au parentId courant, alors on peut passer à l'ID (rootFolders) suivant sans risque de devoir revenir en arrière, car les ID ne peuvent que croître.

Donc c'est bien <0 qu'il faut tester ici.

2024-12-20 08:17 UTC, jcbe-ode commented on conversation/backend/src/main/java/org/entcore/conversation/util/FolderUtil.java
> +public class FolderUtil {
En théorie, oui - idéalement via un ORM existant et optimisé pour.
En pratique, non, car les données sont déjà déserialisées en JSON, et les re-transformer en instances de classe java va à nouveau consommer du CPU, pour rien.

2024-12-20 08:21 UTC, jcbe-ode commented on conversation/backend/src/main/java/org/entcore/conversation/util/MessageUtil.java
> +    static public void computeUsersAndGroupsDisplayNames(
J'avais initialement pensé retourner des uplets, mais on est en Java 8...
Et créer une classe pour retourner 2-3 données à la fois m'a paru inutile.

2024-12-20 15:24 UTC, jcbe-ode commented on conversation/backend/src/main/java/org/entcore/conversation/util/MessageUtil.java
> +     * @param userIndex Map of ID <-> {"id": user ID, "displayName": username}
* Map / JsonObject
Cela ne fait pas de différence pour moi, c'est la même structure de donnée : une collection de clés/valeurs.
En interne, un JsonObject est une instance de LinkedHashMap.
* `userIndex` et `groupIndex` sont au format attendu par un Render de donnée en JSON.

2024-12-20 16:09 UTC, merged